[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@google-cloud/vision", "busboy", "sharp", "jsqr"]

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"