[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/eurocode-mapping.mjs"]
  external_node_modules = ["@google-cloud/vision","@anthropic-ai/sdk","busboy","sharp","jsqr","@neondatabase/serverless","bcryptjs","jsonwebtoken"]

# Rotas limpas para as funções (usando /api/...)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Páginas HTML específicas não devem ser redirecionadas
[[redirects]]
  from = "/init-eurocodes-table.html"
  to = "/init-eurocodes-table.html"
  status = 200
  force = true

[[redirects]]
  from = "/upload-eurocodes.html"
  to = "/upload-eurocodes.html"
  status = 200
  force = true

# Qualquer outro caminho cai no index.html (SPA fallback)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200